### ISSUE TITLE
1.0 release progress tracking

### ISSUE THREAD

**Issue by steveatinfincia** [infincia/pyairview#2]
- [ ] All known and/or required device API commands properly implemented
- [ ] Provide stable public library API
- [ ] Provide alternate non-thread based public API for RF scanning
- Expanded Python version support, at least 2.7 and 3.2+
  - [x] Python 2.7
  - [x] Python 3.2
  - [x] Python 3.3
  - [x] Python 3.4
